name: Check TypeScript code

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check-ts-format:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    - name: Check Formatting of Server lib
      run: npx prettier --check "src/**/*.{ts,tsx}"
      working-directory: packages/typescript/server/

    - name: Check Formatting of Client lib
      run: npx prettier --check "src/**/*.{ts,tsx}"
      working-directory: packages/typescript/client/

    - name: Check Formatting of React lib
      run: npx prettier --check "src/**/*.{ts,tsx}"
      working-directory: packages/typescript/react/

    - name: Check Formatting of Socket.io lib
      run: npx prettier --check "src/**/*.{ts,tsx}"
      working-directory: packages/typescript/socketio/

    - name: Check Formatting of types lib
      run: npx prettier --check "src/**/*.{ts,tsx}"
      working-directory: packages/typescript/types/
